/mm:
    joint_state_controller:
      type: "joint_state_controller/JointStateController"
      publish_rate: 50
  
    mm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint_a1
        - joint_a2
        - joint_a3
        - joint_a4
        - joint_a5
        - joint_a6
        - joint_a7
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.1

      stop_trajectory_duration: 0.5
      state_publish_rate:  50
      action_monitor_rate: 20
      gains:
        joint_a1: {p: 10.0, i: 1, d: 1.0}
        joint_a2: {p: 10.0, i: 1, d: 1.0}
        joint_a3: {p: 10.0, i: 1, d: 1.0}
        joint_a4: {p: 10.0, i: 1, d: 1.0}
        joint_a5: {p: 10.0, i: 1, d: 1.0}
        joint_a6: {p: 10.0, i: 1, d: 1.0}
        joint_a7: {p: 10.0, i: 1, d: 1.0}
